name          'bashtoni-masq'
version       '0.0.1'
source        'UNKNOWN'
author        'bashtoni'
license       'Apache License, Version 2.0'
summary       'Configures masquerading on the server'
description   'Configures IPv4 masquerading'
project_page  'https://github.com/BashtonLtd/puppet-masq'

dependency 'fiddyspence/sysctl', '>= 0.3.3'
dependency 'puppetlabs/firewall', '>= 0.4.2'
